### PR TITLE
fixing build and updating all dependencies to most recent versions

### PR DESCRIPTION
**Pull request by sebest**
When I tried to use coinbase-pro-rs it was not compiling: I had many errors related to serde.

I fixed the errors by adding:
```
features = ["derive"]
```

I noticed that many dependencies are outdated, so I updated to the most recent versions and fixed the code when the API were slightly different.

Also some of the tests are flaky: "check_latency" and "check_full", I increased the timeouts.

### CODE REVIEW

**Comment by inv2004** [comment]
Thank you for the PR. Let me check it, because I run tests during tokio 0.3 update Nov 2020 - not so old

**Comment by sebest** [comment]
I think that the failed test on the second diff are caused by flaky test, it looks like it depends on the coinbase sandbox which seems to be a bit unpredictable.

**Comment by sebest** [comment]
The first diff does not fix tokio build but serde.

**Comment by sebest** [comment]
Hi, any update on this PR? thank you

**Comment by inv2004** [comment]
@sebest Merged. Sorry for delay. will lift cargo soon

**Pull request merged**
