### PR TITLE
Add support for market order with desired amount in base currency, eg BTC if product_id is BTC-USD

### PR DESCRIPTION
**Pull request by sebest**
This diff also adds some missing field in the Product struct

### CODE REVIEW

**Comment by sebest** [comment]
Hi, let me know if you have any comment on this PR

**Comment by inv2004** [comment]
@sebest I am sorry, decided to wait for tests result and lost it from my focus. Thank you for reminder. Merged

**Comment by sebest** [comment]
Thanks @inv2004 , how often to you tag new releases?

**Comment by inv2004** [comment]
@sebest Just did it: 0.6.9

**Pull request merged**
